name: ETF DB Update

on:
  schedule:
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python src/main.py

      - name: Commit DB
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/etf.db
          git commit -m "update etf db" || echo "no changes"
          git push
