name: Update ETF Data

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - run: python src/main.py

    - name: Check changes
      id: check
      run: |
        if git status --porcelain | grep .; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit & Push
      if: steps.check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/ charts/
        git commit -m "update etf data"
        git push
