name: ETF Fetch Databae

on:
  schedule:
    - cron: "0 * * * *"   # 每小時
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps
      run: pip install pandas requests lxml beautifulsoup4 html5lib

    - name: Run ETF pipeline
      run: python tw_etf_data.py

    - name: Commit changes
      id: check
      run: |
        if grep -q "true" changed.flag; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit & Push
      if: steps.check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "update etf data"
        git push
